// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkzmjtiipdfabwealugz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrem1qdGlpcGRmYWJ3ZWFsdWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzI2MzcsImV4cCI6MjA3Mzg0ODYzN30.m6fvIVC86ykkh17-lQqkEE6DT-xpYZUxr73yRSX9ON8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});